#spring.data.mongodb.uri = mongodb://user:secret@mongo1.example.com:12345,mongo2.example.com:23456/test

spring.data.mongodb.uri=spring.data.mongodb.uri=mongodb://mongo:27017/
#spring.data.mongodb.uri=spring.data.mongodb.uri=mongodb://localhost:27017/
